# Generated by Django 4.1.2 on 2022-12-30 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WomensAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admindb',
            new_name='employeedb',
        ),
    ]
