# Generated by Django 4.1.2 on 2022-12-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WomensAdmin', '0003_categorydb'),
    ]

    operations = [
        migrations.CreateModel(
            name='productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(blank=True, max_length=50, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('PDescription', models.CharField(blank=True, max_length=100, null=True)),
                ('PImage', models.ImageField(blank=True, null=True, upload_to='profile')),
                ('Category', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
