# Generated by Django 4.1.2 on 2023-01-20 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WomenWeb', '0005_itemcart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcart',
            old_name='product',
            new_name='Product',
        ),
        migrations.RenameField(
            model_name='itemcart',
            old_name='quantity',
            new_name='Quantity',
        ),
    ]
