# Generated by Django 4.1.2 on 2023-01-20 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WomenWeb', '0006_rename_product_itemcart_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcart',
            old_name='totalprice',
            new_name='Totalprice',
        ),
    ]
